name: Docker Image CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the latest image
      run: docker build -t browserless/chrome:latest .

    - name: Test the latest image
      run: docker run -e CI=true --entrypoint ./test.sh browserless/chrome:latest

    - name: Build the chrome-stable image
      run: docker build --build-arg "USE_CHROME_STABLE=true" --build-arg "PUPPETEER_VERSION=1.15.0" -t browserless/chrome:stable .

    - name: Test the chrome-stable image
      run: docker run -e CI=true --entrypoint ./test.sh browserless/chrome:stable
